# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 05:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playernews',
            name='timestamp',
        ),
        migrations.AlterUniqueTogether(
            name='playernews',
            unique_together=set([('player', 'report', 'impact')]),
        ),
    ]
